version: '2'
services:
  hubot:
    build: .
    restart: always
    links:
        - mongo
    environment:
        - TELEGRAM_TOKEN
        - HUBOT_JENKINS_URL
        - HUBOT_JENKINS_AUTH
        - TRAVELC_USER
        - TRAVELC_PASS
  mongo:
    image: mongo:3.4.2 
    restart: always
    volumes:
        - /opt/servers/mongodb/data:/data/db
